desc 'Android patch update'
private_lane :android_patch_update do
package = load_json(json_path: "package.json")
increment_version_name(
  gradle_file_path: "android/app/build.gradle",
  version_name: package['version']
)
end

desc 'Android minor update'
private_lane :android_minor_update do
package = load_json(json_path: "package.json")
increment_version_name(
  gradle_file_path: "android/app/build.gradle",
  version_name: package['version']
)
increment_version_code(
  gradle_file_path: "android/app/build.gradle",
)
end

desc 'Patch update'
lane :patch_update do
android_patch_update
end

desc 'Minor update'
lane :minor_update do
android_minor_update
end